### ISSUE TITLE
Replace servertree with custom serverview

### ISSUE THREAD

**Issue by Bluscream** [pathmann/pyTSon_repository#9]
Would that be possible? If yes, how? :o A similar approach to the tweakUI example?

Btw it seems like there are still some issues with the plugin:
```
5/21/2017 18:05:08	ClientUI	Info	Calling plugin onMenuItemEvent: scHandlerID=2type=0, menuItemID=91, selectedItemID=0	
5/21/2017 18:05:08	pyTSon.PluginHost.registerCallbackProxy	Info	Callbackproxy DragDropServerviewModel registered	
5/21/2017 18:05:08	pyTSon.PluginHost.unregisterCallbackProxy	Info	Callbackproxy DragDropServerviewModel unregistered	
5/21/2017 18:05:16	pyTSon	Error	Calling onClientMoveEvent failed with error "Error calling method
Traceback (most recent call last):
  File "C:/Users/blusc/AppData/Roaming/TS3Client/plugins/pyTSon/scripts\pluginhost.py", line 403, in callMethod
    meth(*args)
  File "C:/Users/blusc/AppData/Roaming/TS3Client/plugins/pyTSon/include\ts3widgets\serverview.py", line 1077, in onClientMoveEvent
    oldchan.remove(obj)
  File "C:/Users/blusc/AppData/Roaming/TS3Client/plugins/pyTSon/include\ts3widgets\serverview.py", line 105, in remove
    self.clients.remove(obj)
ValueError: list.remove(x): x not in list

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:/Users/blusc/AppData/Roaming/TS3Client/plugins/pyTSon/scripts\pluginhost.py", line 408, in callMethod
    trace=traceback.format_exc()))
OSError: [Errno 22] Invalid argument
"
5/21/2017 18:05:17	pyTSon.ts3widgets	Error	Error getting client talkpower (490): 512
5/21/2017 18:05:17	pyTSon.ts3widgets	Error	Error getting client inputdeactivated flag (490): 512	
```

**Comment by Bluscream** [comment]
Btw the filetransfer dialog looks good but still needs some work due to many errors
<details>
![image](https://cloud.githubusercontent.com/assets/3318223/26286732/967471e0-3e6c-11e7-9548-1f7e97bdbcd5.png)
![image](https://cloud.githubusercontent.com/assets/3318223/26286737/9e87576c-3e6c-11e7-91ac-165aea9d09be.png)
</details>
